db:
  image: postgres:9.4
web:
  build: .
  command: bin/rails s -p 3000 -b '0.0.0.0'
  environment:
    - DATABASE_HOST=db
    - DATABASE_PORT=5432
    - DATABASE_USER=postgres
  ports:
    - "3000:3000"
  links:
    - db
