default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] || ENV['USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  pool: 5

development:
  <<: *default
  database: docker-service-rails_development

test:
  <<: *default
  database: docker-service-rails_test

production:
  <<: *default
  database: docker-service-rails_production
